---
## Common to all the Ceph Debian nodes
#

- name: Fail on unsupported system
  fail: msg="System not supported {{ ansible_system }}"
  when: ansible_system not in ['Linux']

- name: Fail on unsupported architecture
  fail: msg="Architeture not supported {{ ansible_architecture }}"
  when: ansible_architecture not in ['x86_64']

- name: Fail on unsupported distribution
  fail: msg="Distribution not supported {{ ansible_os_family }}"
  when: ansible_os_family not in ['Debian', 'RedHat']

- name: Install dependancies
  apt: pkg={{ item }} state=present update_cache=yes cache_valid_time=3600 # we update the cache just in case...
  with_items:
    - python-pycurl
    - ntp

- name: Install the Ceph key
  apt_key: url={{ apt_key }} state=present

- name: Add Ceph repository
  apt_repository: repo='deb http://ceph.com/debian-{{ ceph_release }}/ {{ ansible_lsb.codename }} main' state=present

- name: Install Ceph
  apt: pkg={{ item }} state=latest
  with_items:
    - ceph
    - ceph-common    #|
    - ceph-fs-common #|--> yes, they are already all dependancies from 'ceph'
    - ceph-fuse      #|--> however while proceding to rolling upgrades and the 'ceph' package upgrade
    - ceph-mds       #|--> they don't get update so we need to force them
    - libcephfs1     #|
    - g++
    - git
    - libffi-dev
    - python-pip
    - python-dev
    - memcached
    - python-memcache
    - python-xattr
    - python-netifaces
    - python-swiftclient

- name: Generate ceph configuration file
  template: src=roles/common/templates/ceph.conf.j2 dest=/etc/ceph/ceph.conf owner=root group=root mode=0644

- name: clone swift repo
  git: repo=https://github.com/openstack/swift dest=/root/swift update=no

- name: use the good branch
  shell: chdir=/root/swift git fetch https://leseb@review.openstack.org/openstack/swift refs/changes/15/60215/9 && git checkout FETCH_HEAD creates=/root/swift/swift/obj/rados_diskfile.py

- name: install swift
  command: chdir=/root/swift python setup.py install creates=/usr/local/bin/swift-form-signature

- name: create swift group
  group: name=swift

- name: create swift user
  user: name=swift

- name: create swift directory
  file: name=/etc/swift state=directory owner=swift group=swift

- name: create swift.conf
  template: src=swift.conf.j2 dest=/etc/swift/swift.conf owner=swift group=swift
